ID_END_USE_APPLIANCE = 1
ID_END_USE_SPACE_COOLING = 2
ID_END_USE_SPACE_HEATING = 3
ID_END_USE_HOT_WATER = 4
ID_END_USE_VENTILATION = 5


ID_ENERGY_CARRIER_ELECTRICITY = 1
ID_ENERGY_CARRIER_RENEWABLES = [1, 12, 13, 14, 15, 19, 26]


DISTRICT_HEATING_TECHNOLOGIES = [11]
GAS_HEATING_TECHNOLOGIES = [21, 24, 26, 31, 41]
SECOND_HEATING_TECHNOLOGIES = [34, 50]
RENEWABLE_MAIN_HEATING_TECHNOLOGIES = [11, 23, 24, 28, 29, 210, 211, 212, 213, 33, 43, 46]


ID_HEATING_SYSTEM_ACTION_NEW = 1
ID_HEATING_SYSTEM_ACTION_SAME = 2
ID_HEATING_SYSTEM_ACTION_DIFFERENT = 3


ID_BUILDING_ACTION_CONSTRUCTION = 1
ID_BUILDING_ACTION_RENOVATION = 2


ID_SECTOR_TERTIARY = 3
ID_SECTOR_RESIDENTIAL = 6
ID_SUBSECTOR_RESIDENTIAL = 61


PROB_POSTPONING_RENOVATION = 0.7


ID_BUILDING_CONSTRUCTION_PERIOD_NEW_BUILDING = 13


HOUSEHOLD_UNIT_USER_IDS = [1, 2, 3, 4, 5]


MANDATORY_RENOVATION_YEAR_DEFAULT = 9999
MANDATORY_RENOVATION_YEAR_MAX_DELAY = 10
MANDATORY_HEATING_SYSTEM_MODERNIZATION_YEAR_DEFAULT = 9999
MANDATORY_HEATING_SYSTEM_MODERNIZATION_YEAR_MAX_DELAY = 10
