ID_END_USE_APPLIANCE = 1
ID_END_USE_SPACE_COOLING = 2
ID_END_USE_SPACE_HEATING = 3
ID_END_USE_HOT_WATER = 4
ID_END_USE_VENTILATION = 5


ID_ENERGY_CARRIER_ELECTRICITY = 1


DISTRICT_HEATING_TECHNOLOGIES = [11]
GAS_HEATING_TECHNOLOGIES = [21, 24, 26, 31, 41]
SECOND_HEATING_TECHNOLOGIES = [34, 50]


ID_HEATING_SYSTEM_ACTION_NEW = 1
ID_HEATING_SYSTEM_ACTION_SAME = 2
ID_HEATING_SYSTEM_ACTION_DIFFERENT = 3
